# Generated by Django 4.2.6 on 2024-01-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_dealtask_delete_taskdeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealtask',
            name='related_task',
        ),
    ]
