# Generated by Django 4.2.6 on 2024-01-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_remove_dealtask_related_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealtask',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
