# Generated by Django 4.2.6 on 2024-01-13 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('deal', '0007_deal_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_deals', to='client.client'),
        ),
    ]
