# Generated by Django 4.2.6 on 2024-01-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_country'),
        ('deal', '0008_alter_deal_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='lead_source',
            new_name='deal_source',
        ),
        migrations.AddField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_deal', to='company.company'),
        ),
        migrations.AddField(
            model_name='deal',
            name='company_email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
