# Generated by Django 4.2.6 on 2023-12-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_organization_productcategory_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cotizacion',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
