# Generated by Django 4.2.6 on 2023-12-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_cotizacion_alter_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cotizacion',
            new_name='product_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
