# Generated by Django 4.2.6 on 2024-01-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='primary_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
