# Generated by Django 4.2.6 on 2024-01-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_primary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
