# Generated by Django 4.2.6 on 2024-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_contact_company_name_remove_contact_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='primary_email',
            field=models.EmailField(max_length=254),
        ),
    ]
