# Generated by Django 4.2.6 on 2024-01-29 01:59

import administration.organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmedia',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organizationmedia',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmedia',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to=administration.organization.models.organization_directory_path, width_field='image_width'),
        ),
    ]
