# Generated by Django 4.2.6 on 2024-01-29 02:07

import administration.organization.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0003_organizationmedia_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmedia',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=models.SET(administration.organization.models.get_sentinel_user), related_name='created_media', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationmedia',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
