# Generated by Django 4.2.6 on 2024-01-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationmedia_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmedia',
            name='image_size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
