# Generated by Django 4.2.6 on 2023-12-17 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import operation.lead.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('country', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('primary_email', models.EmailField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=254)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('start_date_time', models.DateTimeField()),
                ('original_end_date_time', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('dorman', 'Dorman'), ('close_win', 'Close Win'), ('close_lost', 'Close Lost')], default='new', max_length=20)),
                ('is_closed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(on_delete=models.SET(operation.lead.models.get_sentinel_user), related_name='assigned_lead', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(limit_choices_to={'is_selected': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country')),
                ('created_by', models.ForeignKey(on_delete=models.SET(operation.lead.models.get_sentinel_user), related_name='created_lead', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currency')),
                ('last_modified_by', models.ForeignKey(on_delete=models.SET(operation.lead.models.get_sentinel_user), related_name='last_modified_lead', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='organization.organization')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='LeadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_products', to='lead.lead')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('start_date_time', models.DateTimeField()),
                ('original_end_date_time', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('is_closed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lead.lead')),
                ('lead_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lead.leadproduct')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='lead.task')),
                ('related_subtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_subtasks', to='lead.task')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='lead.task')),
            ],
        ),
    ]
