# Generated by Django 4.2.6 on 2023-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='original_end_date_time',
            new_name='end_date_time',
        ),
        migrations.AddField(
            model_name='lead',
            name='extended_end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
