# Generated by Django 4.2.6 on 2023-12-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_organization_productcategory_organization'),
        ('lead', '0002_rename_original_end_date_time_lead_end_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
    ]
