# Generated by Django 4.2.6 on 2023-12-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='product_category',
        ),
    ]
