# Generated by Django 4.2.6 on 2023-12-19 19:02

from django.db import migrations, models
import django.db.models.deletion
import operation.lead.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_cotizacion_product_product_url_and_more'),
        ('lead', '0004_remove_lead_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='product',
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='cotizacion_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadproduct',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_product', to='lead.lead'),
        ),
    ]
