# Generated by Django 4.2.6 on 2023-12-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_cotizacion_product_product_url_and_more'),
        ('lead', '0005_remove_lead_product_leadproduct_cotizacion_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
