# Generated by Django 4.2.6 on 2023-12-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_cotizacion_product_product_url_and_more'),
        ('lead', '0006_alter_leadproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_product', to='product.product'),
        ),
    ]
