# Generated by Django 4.2.6 on 2023-12-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('lead', '0007_alter_leadproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='last_modified_time',
            new_name='modified_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='original_end_date_time',
        ),
        migrations.AddField(
            model_name='task',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='extended_end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='organization.organization'),
            preserve_default=False,
        ),
    ]
