# Generated by Django 4.2.6 on 2024-01-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_alter_lead_start_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_completion_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='extended_end_date_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date_time',
        ),
    ]
