# Generated by Django 4.2.6 on 2024-01-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_leadtask_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadtask',
            name='related_task',
        ),
    ]
