# Generated by Django 4.2.6 on 2024-01-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_remove_leadtask_related_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadtask',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
