# Generated by Django 4.2.6 on 2024-01-11 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('lead', '0017_lead_company_name_lead_description_lead_erased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_leads', to='contact.contact'),
        ),
    ]
