# Generated by Django 4.2.6 on 2024-01-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0018_lead_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('dorman', 'Dorman'), ('close_lost', 'Close Lost')], default='new', max_length=20),
        ),
    ]
