# Generated by Django 4.2.6 on 2024-01-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0019_alter_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
