# Generated by Django 4.2.6 on 2024-01-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('lead', '0020_lead_company_email_lead_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_company', to='company.company'),
            preserve_default=False,
        ),
    ]
