# Generated by Django 4.2.6 on 2023-12-17 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del país', max_length=100)),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^CO[A-Z]{3}$', 'El código debe empezar con CO seguido de tres mayúsculas')])),
                ('is_selected', models.BooleanField(default=False, help_text='Indica si el país está seleccionado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(check=models.Q(('code__regex', '^CO[A-Z]{3}$')), name='El código debe empezar con CO seguido de tres mayúsculas'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('code', 'organization'), name='La combinación de código y organización debe ser única.'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='La combinación de nombre y organización debe ser única.'),
        ),
    ]
