# Generated by Django 4.2.6 on 2024-01-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currency_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
